[package]
name = "dat"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
sqlx = { version = "0.5.13", features = ["postgres","runtime-tokio-rustls"] }
validator = { version = "0.13", features = ["derive"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }